/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

/**
 *
 * @author Danya, Brayan, Luis, Santiago
 */
public class InterfazCalculadora extends javax.swing.JFrame {

    protected static Calculadora calculadora;
    
    /**
     * Creates new form InterfazCalculadora
     */
    public InterfazCalculadora() {
        calculadora = new Calculadora ();
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        chSig = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        mas = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        mul = new javax.swing.JButton();
        div = new javax.swing.JButton();
        pot = new javax.swing.JButton();
        par1 = new javax.swing.JButton();
        par2 = new javax.swing.JButton();
        siete = new javax.swing.JButton();
        ocho = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        cero = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        nueve = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        expresion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jButton20.setBackground(new java.awt.Color(0, 51, 204));
        jButton20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("C");
        jButton20.setBorder(new javax.swing.border.MatteBorder(null));
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        chSig.setBackground(new java.awt.Color(0, 51, 204));
        chSig.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        chSig.setForeground(new java.awt.Color(255, 255, 255));
        chSig.setText("+/-");
        chSig.setBorder(new javax.swing.border.MatteBorder(null));
        chSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chSigActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(0, 51, 204));
        jButton15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("ANS");
        jButton15.setBorder(new javax.swing.border.MatteBorder(null));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        borrar.setBackground(new java.awt.Color(0, 51, 204));
        borrar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        borrar.setForeground(new java.awt.Color(255, 255, 255));
        borrar.setText("Borrar");
        borrar.setBorder(new javax.swing.border.MatteBorder(null));
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        mas.setBackground(new java.awt.Color(0, 51, 204));
        mas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mas.setForeground(new java.awt.Color(255, 255, 255));
        mas.setText("+");
        mas.setBorder(new javax.swing.border.MatteBorder(null));
        mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masActionPerformed(evt);
            }
        });

        menos.setBackground(new java.awt.Color(0, 51, 204));
        menos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        menos.setForeground(new java.awt.Color(255, 255, 255));
        menos.setText("-");
        menos.setBorder(new javax.swing.border.MatteBorder(null));
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        mul.setBackground(new java.awt.Color(0, 51, 204));
        mul.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        mul.setForeground(new java.awt.Color(255, 255, 255));
        mul.setText("*");
        mul.setBorder(new javax.swing.border.MatteBorder(null));
        mul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulActionPerformed(evt);
            }
        });

        div.setBackground(new java.awt.Color(0, 51, 204));
        div.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        div.setForeground(new java.awt.Color(255, 255, 255));
        div.setText("/");
        div.setBorder(new javax.swing.border.MatteBorder(null));
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        pot.setBackground(new java.awt.Color(0, 51, 204));
        pot.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        pot.setForeground(new java.awt.Color(255, 255, 255));
        pot.setText("^");
        pot.setBorder(new javax.swing.border.MatteBorder(null));
        pot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potActionPerformed(evt);
            }
        });

        par1.setBackground(new java.awt.Color(0, 51, 204));
        par1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        par1.setForeground(new java.awt.Color(255, 255, 255));
        par1.setText("(");
        par1.setBorder(new javax.swing.border.MatteBorder(null));
        par1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                par1ActionPerformed(evt);
            }
        });

        par2.setBackground(new java.awt.Color(0, 51, 204));
        par2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        par2.setForeground(new java.awt.Color(255, 255, 255));
        par2.setText(")");
        par2.setBorder(new javax.swing.border.MatteBorder(null));
        par2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                par2ActionPerformed(evt);
            }
        });

        siete.setBackground(new java.awt.Color(0, 0, 0));
        siete.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        siete.setForeground(new java.awt.Color(0, 153, 51));
        siete.setText("7");
        siete.setBorder(new javax.swing.border.MatteBorder(null));
        siete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteActionPerformed(evt);
            }
        });

        ocho.setBackground(new java.awt.Color(0, 0, 0));
        ocho.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ocho.setForeground(new java.awt.Color(0, 153, 51));
        ocho.setText("8");
        ocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoActionPerformed(evt);
            }
        });

        cuatro.setBackground(new java.awt.Color(0, 0, 0));
        cuatro.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cuatro.setForeground(new java.awt.Color(0, 153, 51));
        cuatro.setText("4");
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });

        cinco.setBackground(new java.awt.Color(0, 0, 0));
        cinco.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cinco.setForeground(new java.awt.Color(0, 153, 51));
        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        uno.setBackground(new java.awt.Color(0, 0, 0));
        uno.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        uno.setForeground(new java.awt.Color(0, 153, 51));
        uno.setText("1");
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        cero.setBackground(new java.awt.Color(0, 0, 0));
        cero.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        cero.setForeground(new java.awt.Color(0, 153, 51));
        cero.setText("0");
        cero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroActionPerformed(evt);
            }
        });

        dos.setBackground(new java.awt.Color(0, 0, 0));
        dos.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        dos.setForeground(new java.awt.Color(0, 153, 51));
        dos.setText("2");
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(255, 51, 51));
        jButton11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText(".");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        tres.setBackground(new java.awt.Color(0, 0, 0));
        tres.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tres.setForeground(new java.awt.Color(0, 153, 51));
        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        seis.setBackground(new java.awt.Color(0, 0, 0));
        seis.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        seis.setForeground(new java.awt.Color(0, 153, 51));
        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        nueve.setBackground(new java.awt.Color(0, 0, 0));
        nueve.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nueve.setForeground(new java.awt.Color(0, 153, 51));
        nueve.setText("9");
        nueve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveActionPerformed(evt);
            }
        });

        igual.setBackground(new java.awt.Color(255, 51, 51));
        igual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        igual.setForeground(new java.awt.Color(255, 255, 255));
        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        expresion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chSig, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expresion, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(par1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(par2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cero, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ocho, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nueve, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seis, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(expresion, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chSig, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ocho)
                    .addComponent(nueve))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cuatro)
                            .addComponent(cinco)
                            .addComponent(seis)
                            .addComponent(par1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(par2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uno)
                            .addComponent(dos)
                            .addComponent(tres)
                            .addComponent(mas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(menos, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cero)
                            .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mul, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pot, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void par1ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        expresion.setText(expresion.getText()+"(");
    }                                    

    private void par2ActionPerformed(java.awt.event.ActionEvent evt) {                                     
        expresion.setText(expresion.getText()+")");
    }                                    

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {                                    
        expresion.setText(expresion.getText()+"1");
    }                                   

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {                                      
        expresion.setText(expresion.getText()+"5");
    }                                     

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {                                     
        expresion.setText(expresion.getText()+"6");
    }                                    

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {                                       
        expresion.setText(expresion.getText()+"4");
    }                                      

    private void nueveActionPerformed(java.awt.event.ActionEvent evt) {                                      
        expresion.setText(expresion.getText()+"9");
    }                                     

    private void ochoActionPerformed(java.awt.event.ActionEvent evt) {                                     
        expresion.setText(expresion.getText()+"8");
    }                                    

    private void sieteActionPerformed(java.awt.event.ActionEvent evt) {                                      
        expresion.setText(expresion.getText()+"7");
    }                                     

    private void masActionPerformed(java.awt.event.ActionEvent evt) {                                    
        expresion.setText(expresion.getText()+"+");
    }                                   

    private void mulActionPerformed(java.awt.event.ActionEvent evt) {                                    
        expresion.setText(expresion.getText()+"*");
    }                                   

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        if(calculadora.getExpresion() != null)
           expresion.setText(expresion.getText() + calculadora.getResultado());
        else
            expresion.setText("No prevs Ans");
    }                                         

    private void divActionPerformed(java.awt.event.ActionEvent evt) {                                    
        expresion.setText(expresion.getText()+"/");
    }                                   

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {                                      
        expresion.setText(expresion.getText()+"-");
    }                                     

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String res;
        
        calculadora = new Calculadora (expresion.getText());
        
        if(!expresion.getText().equals("")){
            res = calculadora.resuelveExpresion();
            expresion.setText(res);
        }
        else {
            expresion.setText("");
        }
    }                                     

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        expresion.setText(expresion.getText()+".");
    }                                         

    private void ceroActionPerformed(java.awt.event.ActionEvent evt) {                                     
        expresion.setText(expresion.getText()+"0");
    }                                    

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {                                     
        expresion.setText(expresion.getText()+"3");
    }                                    

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {                                    
        expresion.setText(expresion.getText()+"2");
    }                                   

    private void potActionPerformed(java.awt.event.ActionEvent evt) {                                    
        expresion.setText(expresion.getText()+"^");
    }                                   

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String cad;
        
        cad = expresion.getText();
        if(cad.contains("Error") && cad.contains("No prevs Ans"))
            cad = "";
        else{
            if(cad.length()!=0){
                cad = cad.substring(0,cad.length()-1);
                expresion.setText(cad);
            }
        }
            
    }                                      
    
    public static boolean esNumero(String num){
        boolean res;
        
        try {
            Double.parseDouble(num);
            res = true;
            
        } catch (Exception e){
            res = false;
        }
 
        return res;
    }
    

    private void chSigActionPerformed(java.awt.event.ActionEvent evt) {                                      
        String temporal;
        int tamaho;
        boolean res;
        int i;
        
        temporal = expresion.getText();
        tamaho = temporal.length();
        res = true;
        i = tamaho-1;
        
        if (esNumero(expresion.getText())){ //Caso donde apenas vas a poner el primer número negativo. Por ejemplo: 9.68 y presionas "+/c", entonces es -9.63 el resultado
            expresion.setText("-"+temporal.substring(0));
        }
        else {
            while (i > 0 && res){
                if (temporal.charAt(i) == '(' || temporal.charAt(i) == '+' || temporal.charAt(i) == '/' || temporal.charAt(i) == '*' || temporal.charAt(i) == '-' || temporal.charAt(i) == '^'){
                res = false;
                }
                i--;
            }
            
            expresion.setText(temporal.substring(0, i+2) + "-" + temporal.substring(i+2, tamaho));
        }
    }                                     

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        expresion.setText("");
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton borrar;
    private javax.swing.JButton cero;
    private javax.swing.JButton chSig;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton div;
    private javax.swing.JButton dos;
    private javax.swing.JTextField expresion;
    private javax.swing.JButton igual;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mas;
    private javax.swing.JButton menos;
    private javax.swing.JButton mul;
    private javax.swing.JButton nueve;
    private javax.swing.JButton ocho;
    private javax.swing.JButton par1;
    private javax.swing.JButton par2;
    private javax.swing.JButton pot;
    private javax.swing.JButton seis;
    private javax.swing.JButton siete;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration                   
}
